apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Always
          name: busybox
          command:
            - "sh"
            - "-c"
            - "while true; do sleep 6000; done"
      restartPolicy: Always