apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: busybox-hpa
  namespace: hackdays
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
  metrics:
    - external:
        metric:
          name: not-existant-metrics
          selector:
            matchLabels:
              group_id: order-service
              topic_name: order-topic
        target:
          averageValue: "25"
          type: AverageValue
      type: External
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: busybox